import pytest
from fastapi.testclient import TestClient
from src.api.app import app
import os
import joblib

client = TestClient(app)

@pytest.fixture(scope="module", autouse=True)
def ensure_model():
    """Ensure a dummy model exists for testing so we don't depend on actual training runs."""
    base_dir = os.path.join(os.path.dirname(__file__), "..")
    models_dir = os.path.join(base_dir, "models")
    os.makedirs(models_dir, exist_ok=True)
    model_path = os.path.join(models_dir, "predictive_maintenance_rf_v1.joblib")
    
    # We train a small real model so shap.TreeExplainer doesn't crash on a mock object
    from sklearn.ensemble import RandomForestClassifier
    import numpy as np
    X = np.random.rand(10, 2)
    y = np.random.randint(0, 2, 10)
    real_mock_model = RandomForestClassifier(n_estimators=2, random_state=42)
    real_mock_model.fit(X, y)
    
    fake_data = {
        "model": real_mock_model,
        "features": ["vibration_mean", "temperature_mean"],
        "version": "v1_test"
    }
    
    # Only write if it doesn't exist, to not overwrite a real model if it's there
    # Actually, let's always overwrite it in a test-specific mock, or just use the real one if it exists
    # If the real one exists (from our training script), it's fine. We'll use the real one.
    if not os.path.exists(model_path):
        joblib.dump(fake_data, model_path)
    
    yield
    
    # We could clean it up, but it's fine to leave.

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
    assert "model_version" in response.json()

def test_predict_success():
    # Provide all 26 features generated by Milestone 6
    # For testing, we just need to provide whatever the model expects. 
    # To be safe, we'll provide a full set of realistic dummy features.
    features = {
        "vibration_mean": 1.5,
        "vibration_std": 0.2,
        "vibration_rms": 1.6,
        "vibration_peak": 2.0,
        "vibration_peak_to_peak": 1.0,
        "vibration_variance": 0.04,
        "vibration_kurtosis": -0.5,
        "vibration_skewness": 0.1,
        "vibration_crest_factor": 1.25,
        "vibration_dominant_frequency": 30.0,
        "vibration_dominant_frequency_amplitude": 0.5,
        "temperature_mean": 45.0,
        "temperature_std": 0.5,
        "temperature_min": 44.0,
        "temperature_max": 46.0,
        "temperature_range": 2.0,
        "temperature_trend": 0.1,
        "current_mean": 5.2,
        "current_std": 0.1,
        "current_min": 5.1,
        "current_max": 5.3,
        "current_rms": 5.2,
        "current_range": 0.2,
        "rpm_mean": 1450.0,
        "rpm_std": 10.0,
        "rpm_min": 1430.0,
        "rpm_max": 1470.0,
        "rpm_range": 40.0
    }
    
    response = client.post("/predict", json={"features": features})
    
    # If using the real trained model, this should succeed
    if response.status_code == 400:
        # If it fails with 400, it might be due to missing features. We print to debug.
        print(response.json())
        
    assert response.status_code == 200
    data = response.json()
    assert "failure_probability" in data
    assert "prediction" in data
    assert data["prediction"] in ["NORMAL", "FAILURE_RISK"]
    assert "model_version" in data
    assert "health_score" in data
    assert "risk_level" in data
    assert "baseline_deviations" in data
    assert "explanations" in data
    assert type(data["explanations"]) == list

def test_predict_missing_features():
    features = {
        "vibration_mean": 1.5
    }
    response = client.post("/predict", json={"features": features})
    assert response.status_code == 400
    assert "Missing required feature" in response.json()["detail"]
