package com.pmp.predictivemaintenance.maintenance;

public enum MaintenanceAction {
    INSPECT_VIBRATION_SYSTEM,
    INSPECT_TEMPERATURE_SYSTEM,
    INSPECT_CURRENT_LOAD,
    INSPECT_RPM_SYSTEM,
    GENERAL_MACHINE_INSPECTION,
    SCHEDULE_PREVENTIVE_MAINTENANCE,
    IMMEDIATE_MACHINE_INSPECTION
}
